### ISSUE TITLE
Use of an unsupported fees url for prod

### ISSUE THREAD

**Issue by jaleen** [hmcts/cmc-citizen-frontend#651]
It seems you are using a version of fees which is not supported yet for prod use. URL and transport(http) are subject to change without notice and will impact your services. You started using this URL without any prior notice or consent.

https://github.com/hmcts/cmc-citizen-frontend/blob/dd1cf272a7d1a54ed6ab11e60640867485c334c9/infrastructure/prod.tfvars#L4

**Comment by timja-kainos** [comment]
we asked you and you said yes?

**Comment by timja-kainos** [comment]
Not the right forum for this

**Comment by timja-kainos** [comment]
https://github.com/hmcts/cmc-citizen-frontend/pull/647#discussion_r199453760
